homepage:
    pattern:  /
    defaults: { _controller: OlitazToolboxBundle:Default:index }
regex:
    pattern:  /regex
    defaults: { _controller: OlitazToolboxBundle:Tools:regex }
xml_indent:
    pattern:  /xml-indent
    defaults: { _controller: OlitazToolboxBundle:Tools:xmlIndent }
